### ISSUE TITLE
React Component

### ISSUE THREAD

**Issue by bgub** [favoloso/remarkable-admonitions#18]
Hi, and thanks for the awesome package! The admonitions are really beautiful and clean.

Just so you know, I just created a [React Component](https://github.com/nebrelbug/react-admonitions) based on this package (I gave credit for UI to this package, of course). Should I put together a pull request to add my package to the README, so people who'd like to use it in Docusaurus v2 would see the React Component?

**Comment by leonardfactory** [comment]
Hi @nebrelbug, sure go with a PR. I'd like just to ask you a credit linking to this repo back in the README, if you don't mind.

**Comment by bgub** [comment]
:thumbsup: will do!

Thanks for your great work!

**Comment by leonardfactory** [comment]
Everything's set. Closing this 👍
