### ISSUE TITLE
Admonitions are not being rendered in Docusaurus V2

### ISSUE THREAD

**Issue by prasathsekar** [favoloso/remarkable-admonitions#21]
Hi i am using docusaurus V2. I need admonitions so i used remarkable-admonitions. but it is not supported in docusaurus V2.

I used the below code but it is not working

module.exports = {
  plugins: [
    // Highlight admonitions.
    require('remarkable-admonitions')({ icon: 'svg-inline' })
  ],
};

**Comment by leonardfactory** [comment]
Hi @prasathsekar , as shown in the readme for v2 you can use the [react component](https://github.com/nebrelbug/react-admonitions) 👍
